JAZZMIN_SETTINGS = {
    "site_title": "Hotel Management System Admin",
    "site_header": "Hotel Management System",
    "site_brand": "Hotel Management System",
    "site_logo": None,
    "login_logo": None,
    "login_logo_dark": None,
    "site_icon": None,
    "welcome_sign": "Welcome to Hotel Management System",
    "copyright": "Hotel Management System",
    "search_model": "inventory.Item",
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index"},
        {"name": "API Health", "url": "/api/v1/health/", "new_window": True},
        {"model": "procurement.PurchaseRequisition"},
        {"model": "procurement.PurchaseOrder"},
    ],
    "usermenu_links": [
        {"name": "API Health", "url": "/api/v1/health/", "new_window": True},
        {"model": "audit_logs.AuditLog"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "accounts",
        "accounts.User",
        "departments",
        "departments.Department",
        "departments.Branch",
        "employees",
        "employees.Designation",
        "employees.Employee",
        "vendors",
        "vendors.Supplier",
        "inventory",
        "inventory.Category",
        "inventory.UnitOfMeasure",
        "inventory.Item",
        "inventory.ItemUnitPrice",
        "inventory.StoreLocation",
        "inventory.InventoryBalance",
        "inventory.SupplierItemPrice",
        "inventory.ReorderRule",
        "inventory.StockLedger",
        "inventory.InventoryBatch",
        "inventory.StoreRequisition",
        "inventory.StoreRequisitionItem",
        "inventory.StockIssue",
        "inventory.StockIssueItem",
        "inventory.StoreReturn",
        "inventory.StoreReturnItem",
        "inventory.StockCount",
        "inventory.StockCountItem",
        "inventory.StockTransfer",
        "inventory.StockTransferItem",
        "inventory.StockAdjustment",
        "inventory.StockAdjustmentItem",
        "customers",
        "customers.Customer",
        "customers.CustomerLedger",
        "customers.Payment",
        "customers.PaymentAllocation",
        "sales",
        "sales.Sale",
        "sales.SaleItem",
        "procurement",
        "procurement.PurchaseRequisition",
        "procurement.RequisitionItem",
        "procurement.VendorQuotation",
        "procurement.VendorQuotationItem",
        "procurement.PurchaseOrder",
        "procurement.PurchaseOrderItem",
        "procurement.GoodsReceiptNote",
        "procurement.GoodsReceiptItem",
        "procurement.GoodsInspection",
        "procurement.GoodsInspectionItem",
        "procurement.SupplierReturn",
        "procurement.SupplierReturnItem",
        "approvals",
        "approvals.ApprovalWorkflow",
        "finance",
        "finance.PaymentMethod",
        "finance.CashFlow",
        "finance.DailyCashSummary",
        "finance.BankAccount",
        "finance.BankTransaction",
        "finance.ExpenseCategory",
        "finance.Expense",
        "notifications",
        "notifications.Notification",
        "audit_logs",
        "audit_logs.AuditLog",
        "auth",
        "auth.Group",
    ],
    "custom_links": {
        "vendors": [
            {
                "name": "Vendor API",
                "url": "/api/v1/vendors/",
                "icon": "fas fa-code",
                "permissions": ["vendors.view_supplier"],
                "new_window": True,
            }
        ],
        "inventory": [
            {
                "name": "Items API",
                "url": "/api/v1/items/",
                "icon": "fas fa-code",
                "permissions": ["inventory.view_item"],
                "new_window": True,
            },
            {
                "name": "Stock Ledger API",
                "url": "/api/v1/stock-ledger/",
                "icon": "fas fa-code",
                "permissions": ["inventory.view_stockledger"],
                "new_window": True,
            },
            {
                "name": "Stock Summary Report",
                "url": "/api/v1/reports/stock-summary/",
                "icon": "fas fa-chart-line",
                "permissions": ["inventory.view_inventorybalance"],
                "new_window": True,
            },
            {
                "name": "Low Stock Report",
                "url": "/api/v1/reports/low-stock/",
                "icon": "fas fa-exclamation-triangle",
                "permissions": ["inventory.view_inventorybalance"],
                "new_window": True,
            },
        ],
        "procurement": [
            {
                "name": "Requisitions API",
                "url": "/api/v1/requisitions/",
                "icon": "fas fa-code",
                "permissions": ["procurement.view_purchaserequisition"],
                "new_window": True,
            },
            {
                "name": "Purchase Orders API",
                "url": "/api/v1/purchase-orders/",
                "icon": "fas fa-code",
                "permissions": ["procurement.view_purchaseorder"],
                "new_window": True,
            },
            {
                "name": "GRNs API",
                "url": "/api/v1/grns/",
                "icon": "fas fa-code",
                "permissions": ["procurement.view_goodsreceiptnote"],
                "new_window": True,
            },
            {
                "name": "Procurement Summary",
                "url": "/api/v1/reports/procurement-summary/",
                "icon": "fas fa-chart-pie",
                "permissions": ["procurement.view_purchaseorder"],
                "new_window": True,
            },
        ],
    },
    "icons": {
        "accounts": "fas fa-user-shield",
        "accounts.User": "fas fa-user-tie",
        "auth": "fas fa-users-cog",
        "auth.Group": "fas fa-users",
        "departments": "fas fa-sitemap",
        "departments.Department": "fas fa-building",
        "departments.Branch": "fas fa-hotel",
        "employees": "fas fa-id-card",
        "employees.Designation": "fas fa-user-tag",
        "employees.Employee": "fas fa-user-check",
        "vendors": "fas fa-truck-loading",
        "vendors.Supplier": "fas fa-handshake",
        "inventory": "fas fa-boxes",
        "inventory.Category": "fas fa-tags",
        "inventory.UnitOfMeasure": "fas fa-ruler-combined",
        "inventory.Item": "fas fa-box",
        "inventory.ItemUnitPrice": "fas fa-tags",
        "inventory.StoreLocation": "fas fa-warehouse",
        "inventory.InventoryBalance": "fas fa-layer-group",
        "inventory.InventoryBatch": "fas fa-box-open",
        "inventory.ReorderRule": "fas fa-bell",
        "inventory.SupplierItemPrice": "fas fa-money-bill-wave",
        "inventory.StockLedger": "fas fa-exchange-alt",
        "inventory.StoreRequisition": "fas fa-clipboard-list",
        "inventory.StoreRequisitionItem": "fas fa-list-ul",
        "inventory.StockIssue": "fas fa-dolly-flatbed",
        "inventory.StockIssueItem": "fas fa-list",
        "inventory.StoreReturn": "fas fa-undo",
        "inventory.StoreReturnItem": "fas fa-list",
        "inventory.StockCount": "fas fa-clipboard-check",
        "inventory.StockCountItem": "fas fa-tasks",
        "inventory.StockTransfer": "fas fa-truck-moving",
        "inventory.StockTransferItem": "fas fa-people-carry",
        "inventory.StockAdjustment": "fas fa-sliders-h",
        "inventory.StockAdjustmentItem": "fas fa-balance-scale",
        "customers": "fas fa-address-book",
        "customers.Customer": "fas fa-user-friends",
        "customers.CustomerLedger": "fas fa-book",
        "customers.Payment": "fas fa-receipt",
        "customers.PaymentAllocation": "fas fa-random",
        "sales": "fas fa-cash-register",
        "sales.Sale": "fas fa-shopping-cart",
        "sales.SaleItem": "fas fa-list",
        "procurement": "fas fa-file-invoice-dollar",
        "procurement.PurchaseRequisition": "fas fa-clipboard-list",
        "procurement.RequisitionItem": "fas fa-list-ul",
        "procurement.VendorQuotation": "fas fa-file-signature",
        "procurement.VendorQuotationItem": "fas fa-list",
        "procurement.PurchaseOrder": "fas fa-file-invoice",
        "procurement.PurchaseOrderItem": "fas fa-list-ol",
        "procurement.GoodsReceiptNote": "fas fa-dolly",
        "procurement.GoodsReceiptItem": "fas fa-clipboard-check",
        "procurement.GoodsInspection": "fas fa-search",
        "procurement.GoodsInspectionItem": "fas fa-tasks",
        "procurement.SupplierReturn": "fas fa-undo-alt",
        "procurement.SupplierReturnItem": "fas fa-list",
        "approvals": "fas fa-check-double",
        "approvals.ApprovalWorkflow": "fas fa-tasks",
        "finance": "fas fa-wallet",
        "finance.PaymentMethod": "fas fa-credit-card",
        "finance.CashFlow": "fas fa-money-bill-transfer",
        "finance.DailyCashSummary": "fas fa-calculator",
        "finance.BankAccount": "fas fa-university",
        "finance.BankTransaction": "fas fa-exchange-alt",
        "finance.ExpenseCategory": "fas fa-folder-open",
        "finance.Expense": "fas fa-file-invoice-dollar",
        "notifications": "fas fa-bell",
        "notifications.Notification": "fas fa-bell",
        "reports": "fas fa-chart-line",
        "audit_logs": "fas fa-history",
        "audit_logs.AuditLog": "fas fa-clipboard-check",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": "admin/css/hotel_management_system_admin.css",
    "custom_js": None,
    "use_google_fonts_cdn": False,
    "show_ui_builder": False,
    "show_theme_chooser": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "accounts.User": "collapsible",
        "auth.Group": "vertical_tabs",
        "audit_logs.AuditLog": "single",
    },
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "default_theme_mode": "light",
    "actions_sticky_top": True,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
