# Generated by Django 6.0.6 on 2026-06-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='inventory_changes_applied',
            field=models.BooleanField(default=False),
        ),
    ]
