# Generated by Django 6.0.6 on 2026-07-27 06:24

import core.validators.quantities
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('procurement', '0007_requisitionitem_estimated_unit_cost'),
        ('vendors', '0002_supplier_contact_person_supplier_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=80)),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, validators=[core.validators.quantities.validate_non_negative_decimal])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[core.validators.quantities.validate_non_negative_decimal])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('exception', 'Match Exception'), ('matched', 'Three-way Matched'), ('approved', 'Approved for Payment'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('quantity_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('match_notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='supplier_invoices/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='procurement.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='vendors.supplier')),
            ],
            options={
                'ordering': ('-invoice_date', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[core.validators.quantities.validate_positive_decimal])),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='finance.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.supplierinvoice')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='finance.paymentmethod')),
            ],
            options={
                'ordering': ('-payment_date', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.UniqueConstraint(fields=('supplier', 'invoice_number'), name='unique_supplier_invoice_number'),
        ),
    ]
