# Generated by Django 6.0.6 on 2026-06-15 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_is_active_branch'),
        ('employees', '0002_employee_address_employee_branch_employee_contact_and_more'),
        ('procurement', '0003_goodsreceiptitem_inventory_changes_applied'),
        ('vendors', '0002_supplier_contact_person_supplier_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='control_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferred_requisitions', to='vendors.supplier'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='request_type',
            field=models.CharField(choices=[('department', 'Department requisition'), ('hotel_purchase', 'Hotel purchase requisition')], default='department', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to='departments.department'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('hod_approved', 'Head of Department Approved'), ('procurement_approved', 'Procurement Approved'), ('finance_approved', 'Finance Approved'), ('director_approved', 'Director Approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
    ]
