# Generated by Django 6.0.6 on 2026-06-15 15:43

import core.validators.quantities
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_address_employee_branch_employee_contact_and_more'),
        ('inventory', '0004_alter_stockledger_reference_type_stockcount_and_more'),
        ('procurement', '0004_purchaserequisition_control_notes_and_more'),
        ('vendors', '0002_supplier_contact_person_supplier_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorquotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[core.validators.quantities.validate_non_negative_decimal]),
        ),
        migrations.CreateModel(
            name='GoodsInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_accepted', 'Partially Accepted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('delivery_note_no', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('goods_receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='procurement.goodsreceiptnote')),
                ('inspected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_inspections', to='employees.employee')),
            ],
            options={
                'ordering': ('-inspection_date', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('return_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('reason', models.TextField()),
                ('inventory_changes_applied', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_returns', to='procurement.goodsreceiptnote')),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_returns', to='employees.employee')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_returns', to='inventory.storelocation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_returns', to='vendors.supplier')),
            ],
            options={
                'ordering': ('-return_date', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[core.validators.quantities.validate_positive_decimal])),
                ('base_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_return_items', to='inventory.item')),
                ('supplier_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.supplierreturn')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_return_items', to='inventory.unitofmeasure')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsInspectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=12, validators=[core.validators.quantities.validate_positive_decimal])),
                ('quantity_accepted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('quantity_rejected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('goods_receipt_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_items', to='procurement.goodsreceiptitem')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.goodsinspection')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_items', to='inventory.item')),
            ],
            options={
                'ordering': ('item__name',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('inspection', 'goods_receipt_item'), name='unique_inspection_receipt_item')],
            },
        ),
        migrations.CreateModel(
            name='VendorQuotationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[core.validators.quantities.validate_positive_decimal])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[core.validators.quantities.validate_positive_decimal])),
                ('delivery_days', models.PositiveIntegerField(default=0)),
                ('selected', models.BooleanField(default=False)),
                ('selection_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='inventory.item')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.vendorquotation')),
                ('requisition_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='procurement.requisitionitem')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='inventory.unitofmeasure')),
            ],
            options={
                'ordering': ('item__name',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('quotation', 'requisition_item', 'unit'), name='unique_quotation_requisition_item_unit')],
            },
        ),
    ]
