# Generated by Codex on 2026-06-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employee_address_employee_branch_employee_contact_and_more"),
        ("procurement", "0005_alter_vendorquotation_total_amount_goodsinspection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="sent_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_purchase_orders",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="sent_to_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
