# Generated by Django 6.0.6 on 2026-07-27 06:24

import core.validators.quantities
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_purchaseorder_supplier_send_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='estimated_unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[core.validators.quantities.validate_non_negative_decimal]),
        ),
    ]
