# Generated by Django 6.0.6 on 2026-07-27 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_branch_hotel_profile_fields'),
        ('procurement', '0007_requisitionitem_estimated_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='direct_issue_department',
            field=models.ForeignKey(blank=True, help_text='Use instead of a store when accepted goods go directly to a department.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_goods_receipts', to='departments.department'),
        ),
    ]
