# Generated by Django 6.0.6 on 2026-07-27 09:23

import core.validators.quantities
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def populate_grn_numbers(apps, schema_editor):
    GoodsReceiptNote = apps.get_model('procurement', 'GoodsReceiptNote')
    counters = {}
    for receipt in GoodsReceiptNote.objects.order_by('received_date', 'created_at'):
        year = receipt.received_date.year
        counters[year] = counters.get(year, 0) + 1
        receipt.grn_number = f"GRN-{year}-{counters[year]:05d}"
        receipt.save(update_fields=['grn_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_address_employee_branch_employee_contact_and_more'),
        ('procurement', '0008_goodsreceiptitem_direct_issue_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='delivery_note_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='grn_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_goods_receipts', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='vendorquotation',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorquotation',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[core.validators.quantities.validate_non_negative_decimal]),
        ),
        migrations.AddField(
            model_name='vendorquotation',
            name='evaluation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorquotation',
            name='evaluation_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[core.validators.quantities.validate_non_negative_decimal]),
        ),
        migrations.AddField(
            model_name='vendorquotation',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vendorquotation',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[core.validators.quantities.validate_non_negative_decimal]),
        ),
        migrations.AddField(
            model_name='vendorquotation',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[core.validators.quantities.validate_non_negative_decimal]),
        ),
        migrations.AddField(
            model_name='vendorquotation',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(populate_grn_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='grn_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
