# Generated by Django 6.0.6 on 2026-07-27 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_address_employee_branch_employee_contact_and_more'),
        ('procurement', '0009_goodsreceiptnote_delivery_note_no_and_more'),
        ('vendors', '0002_supplier_contact_person_supplier_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='email_status',
            field=models.CharField(default='not_sent', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='last_email_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_acknowledged_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='supplierreturn',
            name='credit_note_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplierreturn',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierreturn',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_supplier_returns', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='supplierreturn',
            name='replacement_expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierreturn',
            name='replacement_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierreturn',
            name='replacement_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierreturn',
            name='supplier_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierreturn',
            name='supplier_acknowledged_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='ProcurementAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('quotation', 'Supplier quotation'), ('purchase_order', 'Purchase order'), ('grn', 'Goods receipt'), ('inspection', 'Inspection'), ('supplier_return', 'Supplier return')], max_length=30)),
                ('document_id', models.UUIDField(db_index=True)),
                ('category', models.CharField(choices=[('quotation', 'Quotation'), ('delivery_note', 'Delivery note'), ('invoice', 'Invoice'), ('inspection_photo', 'Inspection photograph'), ('supporting', 'Supporting document')], default='supporting', max_length=30)),
                ('file', models.FileField(upload_to='procurement/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcurementCommunication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(default='email', max_length=20)),
                ('direction', models.CharField(default='outbound', max_length=20)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='procurement.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_communications', to='vendors.supplier')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
