# Generated by Django 6.0.6 on 2026-07-29 15:48

import core.validators.quantities
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_requisition_data(apps, schema_editor):
    PurchaseRequisition = apps.get_model("procurement", "PurchaseRequisition")
    RequisitionHistory = apps.get_model("procurement", "RequisitionHistory")
    RequisitionItem = apps.get_model("procurement", "RequisitionItem")
    RequisitionSequence = apps.get_model("procurement", "RequisitionSequence")

    counters = {}
    requisitions = PurchaseRequisition.objects.select_related(
        "requester__branch__hotel",
        "branch__hotel",
    ).order_by("created_at", "id")
    for requisition in requisitions:
        branch = requisition.branch
        if branch is None and requisition.requester_id:
            branch = requisition.requester.branch
            requisition.branch = branch
        hotel = requisition.hotel
        if hotel is None and branch is not None:
            hotel = branch.hotel
            requisition.hotel = hotel
        requisition.currency = (hotel.currency if hotel else "") or "UGX"

        year = requisition.created_at.year
        scope = "HOTEL"
        if branch is not None:
            scope = (branch.branch_code or str(branch.pk)[:8]).strip().upper()
        key = (scope, year)
        counters[key] = counters.get(key, 0) + 1
        requisition.requisition_number = (
            f"PR-{scope}-{year}-{counters[key]:05d}"
        )

        timestamp_updates = {
            "submitted": "submitted_at",
            "hod_approved": "submitted_at",
            "procurement_approved": "submitted_at",
            "finance_approved": "submitted_at",
            "director_approved": "submitted_at",
            "approved": "approved_at",
            "rejected": "rejected_at",
            "cancelled": "cancelled_at",
        }
        timestamp_field = timestamp_updates.get(requisition.status)
        if timestamp_field and not getattr(requisition, timestamp_field):
            setattr(requisition, timestamp_field, requisition.updated_at)
        requisition.save()

        RequisitionHistory.objects.create(
            requisition=requisition,
            action="migrated_existing_requisition",
            previous_status="",
            new_status=requisition.status,
            performed_by=requisition.created_by,
            comments="Existing requisition registered in the formal lifecycle history.",
            created_by=requisition.created_by,
        )

    for (scope, year), current_value in counters.items():
        RequisitionSequence.objects.update_or_create(
            scope=scope,
            year=year,
            defaults={"current_value": current_value},
        )

    for line in RequisitionItem.objects.select_related("item").all():
        line.description = line.description or line.item.name
        line.unit_id = line.unit_id or line.item.base_unit_id
        if line.requisition.status in (
            "approved",
            "partially_ordered",
            "ordered",
            "partially_received",
            "fulfilled",
            "closed",
        ):
            line.approved_quantity = line.approved_quantity or line.quantity
        line.save(
            update_fields=["description", "unit", "approved_quantity", "updated_at"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_branch_hotel_profile_fields'),
        ('inventory', '0012_stockadjustment_approved_at_and_more'),
        ('organization', '0001_initial'),
        ('procurement', '0011_procurementattachment_database_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to='departments.branch'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='currency',
            field=models.CharField(default='UGX', max_length=10),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to='organization.hotel'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='requisition_number',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='approved_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[core.validators.quantities.validate_positive_decimal]),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisition_items', to='inventory.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('returned', 'Returned for correction'), ('hod_approved', 'Head of Department Approved'), ('procurement_approved', 'Procurement Approved'), ('finance_approved', 'Finance Approved'), ('director_approved', 'Director Approved'), ('approved', 'Approved'), ('partially_ordered', 'Partially Ordered'), ('ordered', 'Fully Ordered'), ('partially_received', 'Partially Received'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
        migrations.CreateModel(
            name='RequisitionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
                ('comments', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_history_events', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='procurement.purchaserequisition')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequisitionSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField()),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('scope', '-year'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('scope', 'year'), name='unique_requisition_sequence_scope_year')],
            },
        ),
        migrations.RunPython(
            backfill_requisition_data,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='requisition_number',
            field=models.CharField(blank=True, db_index=True, max_length=60, unique=True),
        ),
    ]
