# Generated by Django 6.0.6 on 2026-08-03 15:04

import django.db.models.deletion
from django.db import migrations, models


def backfill_approved_destinations(apps, schema_editor):
    PurchaseOrderItem = apps.get_model('procurement', 'PurchaseOrderItem')
    RequisitionItem = apps.get_model('procurement', 'RequisitionItem')
    GoodsReceiptItem = apps.get_model('procurement', 'GoodsReceiptItem')
    for line in PurchaseOrderItem.objects.select_related('purchase_order').iterator():
        receipt = GoodsReceiptItem.objects.filter(purchase_order_item_id=line.id).order_by('-created_at').first()
        if receipt and receipt.direct_issue_department_id:
            line.destination_type = 'workspace'
            line.destination_department_id = receipt.direct_issue_department_id
            line.destination_store_id = None
            line.destination_justification = 'Historical direct-delivery route inferred from the goods receipt.'
        else:
            line.destination_type = 'store'
            line.destination_store_id = (receipt.store_id if receipt else None) or line.purchase_order.store_id
        line.save(update_fields=['destination_type', 'destination_store', 'destination_department', 'destination_justification'])
        RequisitionItem.objects.filter(
            requisition_id=line.purchase_order.requisition_id,
            item_id=line.item_id,
        ).update(
            destination_type=line.destination_type,
            destination_store_id=line.destination_store_id,
            destination_department_id=line.destination_department_id,
            destination_justification=line.destination_justification,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_branch_hotel_profile_fields'),
        ('inventory', '0016_supplieritemprice_currency_and_more'),
        ('procurement', '0013_purchaserequisition_procurement_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='destination_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planned_direct_purchase_order_receipts', to='departments.department'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='destination_justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='destination_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planned_purchase_order_receipts', to='inventory.storelocation'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='destination_type',
            field=models.CharField(choices=[('store', 'Store inventory'), ('workspace', 'Direct to workspace')], default='store', max_length=20),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='destination_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planned_direct_requisition_receipts', to='departments.department'),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='destination_justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='destination_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planned_requisition_receipts', to='inventory.storelocation'),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='destination_type',
            field=models.CharField(choices=[('store', 'Store inventory'), ('workspace', 'Direct to workspace')], default='store', max_length=20),
        ),
        migrations.RunPython(backfill_approved_destinations, migrations.RunPython.noop),
    ]
