# Generated by Django 6.0.6 on 2026-08-15 06:46

import core.validators.quantities
import django.db.models.deletion
import uuid
from datetime import timedelta
from django.conf import settings
from django.db import migrations, models


def bootstrap_control_fields(apps, schema_editor):
    Sequence = apps.get_model('procurement', 'ProcurementDocumentSequence')
    PurchaseRequisition = apps.get_model('procurement', 'PurchaseRequisition')
    PurchaseOrder = apps.get_model('procurement', 'PurchaseOrder')
    PurchaseOrderItem = apps.get_model('procurement', 'PurchaseOrderItem')
    GoodsReceiptNote = apps.get_model('procurement', 'GoodsReceiptNote')
    StoreRequisition = apps.get_model('inventory', 'StoreRequisition')

    def highest_numeric(model, field):
        highest = 0
        for value in model.objects.values_list(field, flat=True).iterator():
            text = str(value or '').strip()
            if text.isdigit():
                highest = max(highest, int(text))
        return highest

    for document_type, model, field in (
        ('requisition', PurchaseRequisition, 'requisition_number'),
        ('lpo', PurchaseOrder, 'po_number'),
        ('grn', GoodsReceiptNote, 'grn_number'),
        ('store_requisition', StoreRequisition, 'requisition_no'),
    ):
        Sequence.objects.update_or_create(
            document_type=document_type,
            defaults={'current_value': highest_numeric(model, field)},
        )

    for line in PurchaseOrderItem.objects.filter(procurement_quantity__isnull=True).iterator():
        line.procurement_quantity = line.quantity
        line.procurement_base_quantity = line.base_quantity
        line.save(update_fields=('procurement_quantity', 'procurement_base_quantity'))

    for order in PurchaseOrder.objects.filter(valid_until__isnull=True).iterator():
        reference = order.submitted_for_approval_at or order.created_at
        if reference:
            order.valid_until = reference.date() + timedelta(days=7)
            order.save(update_fields=('valid_until',))


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_supplieritemprice_quotation_reference_and_more'),
        ('procurement', '0017_purchaseorderitem_requisition_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='supplier_invoice_no',
            field=models.CharField(blank=True, help_text='Invoice reference physically presented by the supplier.', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=0, help_text='Supplier lead time captured from the selected quotation/catalogue.'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Last date on which the supplier may accept this LPO.', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='finance_approved_base_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[core.validators.quantities.validate_non_negative_decimal]),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='finance_approved_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Finance-approved quantity; blank means Finance retained the Procurement quantity.', max_digits=12, null=True, validators=[core.validators.quantities.validate_non_negative_decimal]),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='finance_reduction_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='procurement_base_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[core.validators.quantities.validate_non_negative_decimal]),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='procurement_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity requested by Procurement before Finance review.', max_digits=12, null=True, validators=[core.validators.quantities.validate_non_negative_decimal]),
        ),
        migrations.AlterField(
            model_name='procurementattachment',
            name='document_type',
            field=models.CharField(choices=[('supplier_catalogue', 'Supplier catalogue quotation'), ('purchase_requisition', 'Purchase requisition'), ('quotation', 'Supplier quotation'), ('purchase_order', 'Purchase order'), ('grn', 'Goods receipt'), ('inspection', 'Inspection'), ('supplier_return', 'Supplier return')], max_length=30),
        ),
        migrations.CreateModel(
            name='ProcurementDocumentSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(max_length=30, unique=True)),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('document_type',),
                'abstract': False,
            },
        ),
        migrations.RunPython(bootstrap_control_fields, migrations.RunPython.noop),
        migrations.CreateModel(
            name='PurchaseOrderActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=80)),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
                ('comments', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_activities', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='procurement.purchaseorder')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderPrintRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('print_number', models.PositiveIntegerField()),
                ('classification', models.CharField(choices=[('original', 'Original'), ('copy', 'Copy')], max_length=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_records', to='procurement.purchaseorder')),
            ],
            options={
                'ordering': ('print_number',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('purchase_order', 'print_number'), name='unique_purchase_order_print_number'), models.UniqueConstraint(condition=models.Q(('classification', 'original')), fields=('purchase_order', 'classification'), name='one_original_purchase_order_print')],
            },
        ),
    ]
