# Generated by Django 6.0.6 on 2026-08-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0018_goodsreceiptnote_supplier_invoice_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('returned', 'Returned for correction'), ('hod_approved', 'Department Reviewed'), ('procurement_approved', 'Procurement Approved'), ('finance_approved', 'Finance Approved'), ('director_approved', 'General Manager Approved'), ('approved', 'Approved'), ('partially_ordered', 'Partially Ordered'), ('ordered', 'Fully Ordered'), ('partially_received', 'Partially Received'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
    ]
