# Generated by Django 6.0.6 on 2026-08-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0019_consolidate_operational_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition',
            name='procurement_source',
            field=models.CharField(choices=[('store_requisition', 'Store Keeper requisition'), ('store_shortage', 'Store shortage (legacy)'), ('manual', 'Manual procurement'), ('capital_asset', 'Capital asset'), ('emergency', 'Emergency purchase'), ('project', 'Project purchase'), ('service', 'Service / non-stock purchase')], db_index=True, default='manual', max_length=30),
        ),
    ]
