# Generated by Django 6.0.6 on 2026-08-28 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_complete_received_department_requisitions'),
        ('procurement', '0026_normalize_open_lpo_base_uom'),
        ('vendors', '0003_alter_supplier_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='procurement_supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier selected by Procurement for this requisition line.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocated_requisition_items', to='vendors.supplier'),
        ),
        migrations.AlterField(
            model_name='requisitionitem',
            name='procurement_supplier_price',
            field=models.ForeignKey(blank=True, help_text='Vetted supplier catalogue quotation used for the allocation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocated_requisition_items', to='inventory.supplieritemprice'),
        ),
    ]
