# Generated by Django 6.0.6 on 2026-09-03 16:58

import core.validators.quantities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0031_sync_lpo_physical_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='finance_approved_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Finance-approved quantity; blank means Finance retained the Purchasing Manager quantity.', max_digits=12, null=True, validators=[core.validators.quantities.validate_non_negative_decimal]),
        ),
    ]
