# Generated by Django 6.0.6 on 2026-06-15 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_is_active_branch'),
        ('employees', '0002_employee_address_employee_branch_employee_contact_and_more'),
        ('inventory', '0002_itemunitprice_stockadjustment_stockadjustmentitem_and_more'),
        ('procurement', '0002_goodsreceiptnote_note_purchaseorder_expected_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybatch',
            name='purchase_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_batches', to='procurement.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='itemunitprice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemunitprice',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_prices', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_adjustments', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustment_items', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='stock_adjustment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockadjustment'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_transfers', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfer_requests', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfer_items', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='stock_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer'),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_locations', to='departments.branch'),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.storelocation'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.storelocation'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='inventory.storelocation'),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_batches', to='inventory.storelocation'),
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='inventory.storelocation'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.storelocation'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfer_items', to='inventory.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='stockadjustmentitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustment_items', to='inventory.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='itemunitprice',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_prices', to='inventory.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='item',
            name='base_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_items', to='inventory.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='supplieritemprice',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_item_prices', to='inventory.unitofmeasure'),
        ),
        migrations.AddConstraint(
            model_name='storelocation',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_branch_store_location'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.UniqueConstraint(fields=('item', 'store'), name='unique_item_store_inventory_balance'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferitem',
            constraint=models.UniqueConstraint(fields=('stock_transfer', 'item', 'unit'), name='unique_stock_transfer_item_unit'),
        ),
        migrations.AddConstraint(
            model_name='stockadjustmentitem',
            constraint=models.UniqueConstraint(fields=('stock_adjustment', 'item', 'unit'), name='unique_stock_adjustment_item_unit'),
        ),
        migrations.AddConstraint(
            model_name='itemunitprice',
            constraint=models.UniqueConstraint(fields=('item', 'unit'), name='unique_item_unit_price'),
        ),
    ]
