# Generated by Django 6.0.6 on 2026-06-15 15:43

import core.validators.quantities
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_is_active_branch'),
        ('employees', '0002_employee_address_employee_branch_employee_contact_and_more'),
        ('inventory', '0003_inventorybatch_purchase_order_item_and_more'),
        ('vendors', '0002_supplier_contact_person_supplier_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='reference_type',
            field=models.CharField(choices=[('goods_receipt', 'Goods Receipt'), ('purchase_order', 'Purchase Order'), ('stock_adjustment', 'Stock Adjustment'), ('stock_issue', 'Stock Issue'), ('stock_transfer', 'Stock Transfer'), ('sale', 'Sale'), ('return_to_vendor', 'Return to Vendor'), ('store_return', 'Store Return'), ('stock_count', 'Stock Count')], max_length=50),
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('count_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('inventory_changes_applied', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_counts', to='employees.employee')),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='employees.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='inventory.storelocation')),
            ],
            options={
                'ordering': ('-count_date', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requisition_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('partially_approved', 'Partially Approved'), ('rejected', 'Rejected'), ('partially_issued', 'Partially Issued'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_store_requisitions', to='employees.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_requisitions', to='departments.department')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_requisitions', to='employees.employee')),
                ('store', models.ForeignKey(help_text='Store expected to issue the requested stock.', on_delete=django.db.models.deletion.PROTECT, related_name='store_requisitions', to='inventory.storelocation')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('received_by_name', models.CharField(blank=True, max_length=150)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('inventory_changes_applied', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_issues', to='employees.employee')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_stock_issues', to='employees.employee')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_issues', to='inventory.storelocation')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_issues', to='inventory.storerequisition')),
            ],
            options={
                'ordering': ('-issue_date', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreRequisitionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=12, validators=[core.validators.quantities.validate_positive_decimal])),
                ('base_quantity_requested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('quantity_approved', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[core.validators.quantities.validate_non_negative_decimal])),
                ('quantity_issued', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[core.validators.quantities.validate_non_negative_decimal])),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_requisition_items', to='inventory.item')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.storerequisition')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_requisition_items', to='inventory.unitofmeasure')),
            ],
            options={
                'ordering': ('item__name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockIssueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[core.validators.quantities.validate_positive_decimal])),
                ('base_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockissue')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_issue_items', to='inventory.item')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_issue_items', to='inventory.unitofmeasure')),
                ('requisition_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_issue_items', to='inventory.storerequisitionitem')),
            ],
            options={
                'ordering': ('item__name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('return_date', models.DateField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('inventory_changes_applied', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_returns', to='departments.department')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_store_returns', to='employees.employee')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_returns', to='inventory.storelocation')),
            ],
            options={
                'ordering': ('-return_date', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[core.validators.quantities.validate_positive_decimal])),
                ('base_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('condition_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_return_items', to='inventory.item')),
                ('store_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.storereturn')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_return_items', to='inventory.unitofmeasure')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReorderRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minimum_level', models.DecimalField(decimal_places=2, max_digits=12, validators=[core.validators.quantities.validate_non_negative_decimal])),
                ('reorder_quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[core.validators.quantities.validate_positive_decimal])),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='inventory.item')),
                ('preferred_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferred_reorder_rules', to='vendors.supplier')),
                ('store', models.ForeignKey(blank=True, help_text='Leave blank to use this rule as the default for all stores.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='inventory.storelocation')),
            ],
            options={
                'ordering': ('item__name', 'store__name'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('item', 'store'), name='unique_item_store_reorder_rule')],
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[core.validators.quantities.validate_non_negative_decimal])),
                ('physical_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[core.validators.quantities.validate_non_negative_decimal])),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_count_items', to='inventory.item')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockcount')),
            ],
            options={
                'ordering': ('item__name',),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('stock_count', 'item'), name='unique_stock_count_item')],
            },
        ),
        migrations.AddConstraint(
            model_name='storerequisitionitem',
            constraint=models.UniqueConstraint(fields=('requisition', 'item', 'unit'), name='unique_store_requisition_item_unit'),
        ),
        migrations.AddConstraint(
            model_name='stockissueitem',
            constraint=models.UniqueConstraint(fields=('issue', 'requisition_item', 'unit'), name='unique_stock_issue_requisition_item_unit'),
        ),
    ]
