# Generated by ChatGPT

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_stockledger_reference_type_stockcount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("consumable_expense", "Consumable / Operating Expense"),
                    ("resale_revenue", "Resale / Revenue Item"),
                    ("production_input", "Production Input"),
                    ("fixed_asset", "Fixed Asset"),
                    ("service_supply", "Service Supply"),
                ],
                default="consumable_expense",
                help_text="Classifies whether the item is an operating expense, revenue/resale item, production input, fixed asset, or service supply.",
                max_length=30,
            ),
        ),
    ]
