# Generated by Django 6.0.6 on 2026-06-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='business_type',
            field=models.CharField(choices=[('consumable_expense', 'Consumable / Operating Expense'), ('resale_revenue', 'Resale / Revenue Item'), ('fixed_asset', 'Fixed Asset')], default='consumable_expense', help_text='Classifies whether the item is an operating expense, revenue/resale item, production input, fixed asset, or service supply.', max_length=30),
        ),
    ]
