# Generated by Django 6.0.6 on 2026-06-27 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_category_codes(apps, schema_editor):
    Category = apps.get_model("inventory", "Category")
    used_codes = set()

    for category in Category.objects.order_by("created_at", "id"):
        base = "".join(
            character for character in category.name.upper() if character.isalnum()
        )[:3] or "CAT"
        code = base
        suffix = 2
        while code in used_codes:
            code = f"{base}-{suffix}"
            suffix += 1
        category.code = code
        category.save(update_fields=["code"])
        used_codes.add(code)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_item_business_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='business_type',
            field=models.CharField(choices=[('consumable_expense', 'Consumable / Operating Expense'), ('resale_revenue', 'Resale / Revenue Item'), ('fixed_asset', 'Fixed Asset')], default='consumable_expense', help_text='Classifies whether the item is an operating expense, revenue/resale item, fixed asset, or service supply.', max_length=30),
        ),
        migrations.RunPython(populate_category_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='category_cannot_parent_itself'),
        ),
    ]
