# Generated by Django 6.0.6 on 2026-07-27 06:24

import core.validators.quantities
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_category_code_category_is_active_category_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='batch_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='expiry_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='maximum_level',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional maximum stock holding in base units.', max_digits=12, null=True, validators=[core.validators.quantities.validate_non_negative_decimal]),
        ),
        migrations.AddField(
            model_name='itemunitprice',
            name='role',
            field=models.CharField(choices=[('base', 'Base unit'), ('purchase', 'Purchase unit'), ('issue', 'Issue unit'), ('alternate', 'Alternate unit')], default='alternate', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='business_type',
            field=models.CharField(choices=[('consumable_expense', 'Consumable / Operating Expense'), ('resale_revenue', 'Resale / Revenue Item'), ('fixed_asset', 'Fixed Asset'), ('service', 'Service')], default='consumable_expense', help_text='Classifies whether the item is an operating expense, revenue/resale item, fixed asset, or service supply.', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='itemunitprice',
            constraint=models.UniqueConstraint(condition=models.Q(('role__in', ('purchase', 'issue'))), fields=('item', 'role'), name='unique_primary_article_unit_role'),
        ),
    ]
