# Generated by Django 6.0.6 on 2026-07-27 06:29

import core.validators.quantities
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_branch_hotel_profile_fields'),
        ('inventory', '0008_item_batch_tracking_item_expiry_tracking_and_more'),
        ('procurement', '0007_requisitionitem_estimated_unit_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[core.validators.quantities.validate_positive_decimal])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15, validators=[core.validators.quantities.validate_non_negative_decimal])),
                ('consumed_on', models.DateField()),
                ('purpose', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_consumption', to='departments.department')),
                ('goods_receipt_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_consumption_posting', to='procurement.goodsreceiptitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_consumption', to='inventory.item')),
                ('stock_issue_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumption_posting', to='inventory.stockissueitem')),
            ],
            options={
                'ordering': ('-consumed_on', '-created_at'),
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('goods_receipt_item__isnull', True), ('stock_issue_item__isnull', False)), models.Q(('goods_receipt_item__isnull', False), ('stock_issue_item__isnull', True)), _connector='OR'), name='consumption_has_one_source')],
            },
        ),
    ]
