# Generated by Django 6.0.6 on 2026-07-27 07:08

import core.validators.quantities
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_departmentconsumption'),
        ('vendors', '0002_supplier_contact_person_supplier_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplieritemprice',
            options={'ordering': ('item__name', '-is_preferred', 'supplier__name')},
        ),
        migrations.AddField(
            model_name='supplieritemprice',
            name='is_preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplieritemprice',
            name='last_quoted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplieritemprice',
            name='minimum_order_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, validators=[core.validators.quantities.validate_positive_decimal]),
        ),
        migrations.AddField(
            model_name='supplieritemprice',
            name='supplier_sku',
            field=models.CharField(blank=True, help_text="Supplier's own catalogue or product reference.", max_length=80),
        ),
        migrations.AddConstraint(
            model_name='supplieritemprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_preferred', True)), fields=('item',), name='unique_preferred_supplier_per_item'),
        ),
    ]
