# Generated by Django 6.0.6 on 2026-07-27 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_address_employee_branch_employee_contact_and_more'),
        ('inventory', '0011_inventorybalance_quantity_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_stock_transfers', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_stock_transfers', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='storerequisition',
            name='approval_comments',
            field=models.TextField(blank=True),
        ),
    ]
