# Generated by Django 6.0.6 on 2026-08-15 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_gender'),
        ('inventory', '0016_supplieritemprice_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieritemprice',
            name='quotation_reference',
            field=models.CharField(blank=True, help_text='Supplier quotation number or reference for this quoted price.', max_length=100),
        ),
        migrations.AddField(
            model_name='supplieritemprice',
            name='quotation_valid_until',
            field=models.DateField(blank=True, help_text='Expiry date stated on the supplier quotation.', null=True),
        ),
        migrations.CreateModel(
            name='StoreKeeperAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_keeper_assignments', to='employees.employee')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keeper_assignments', to='inventory.storelocation')),
            ],
            options={
                'ordering': ('store__name', 'employee__user__username'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('store', 'employee'), name='unique_store_keeper_assignment')],
            },
        ),
    ]
