# Generated by Django 6.0.6 on 2026-07-27 06:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        ('departments', '0003_branch_hotel_profile_fields'),
        ('employees', '0002_employee_address_employee_branch_employee_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalworkflow',
            name='stage_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ApprovalMatrixRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('document_type', models.CharField(choices=[('purchase_requisition', 'Purchase Requisition'), ('purchase_order', 'Local Purchase Order'), ('stock_adjustment', 'Stock Adjustment'), ('stock_count', 'Stock Count')], max_length=40)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('stage', models.PositiveIntegerField()),
                ('stage_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_matrix_assignments', to='employees.employee')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_matrix_rules', to='departments.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_matrix_rules', to='departments.department')),
            ],
            options={
                'ordering': ('document_type', 'minimum_amount', 'stage'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='matrix_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_steps', to='approvals.approvalmatrixrule'),
        ),
        migrations.AddConstraint(
            model_name='approvalmatrixrule',
            constraint=models.UniqueConstraint(fields=('document_type', 'branch', 'department', 'minimum_amount', 'stage'), name='unique_approval_matrix_stage'),
        ),
        migrations.AddConstraint(
            model_name='approvalmatrixrule',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_amount__isnull', True), ('maximum_amount__gte', models.F('minimum_amount')), _connector='OR'), name='approval_matrix_valid_amount_range'),
        ),
    ]
