# Generated by Django 6.0.6 on 2026-07-29 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_approval_routing(apps, schema_editor):
    ApprovalMatrixRule = apps.get_model("approvals", "ApprovalMatrixRule")
    ApprovalWorkflow = apps.get_model("approvals", "ApprovalWorkflow")

    generic_department_stages = ApprovalMatrixRule.objects.filter(
        document_type="purchase_requisition",
        department__isnull=True,
        stage=1,
        stage_name__icontains="department",
    )
    generic_department_stages.update(
        assignment_type="department_head",
        approver=None,
        approver_role=None,
    )

    for approval in ApprovalWorkflow.objects.exclude(status="pending").select_related(
        "approver__user"
    ):
        approval.decided_at = approval.updated_at
        approval.decided_by_id = approval.approver.user_id
        approval.save(update_fields=["decided_at", "decided_by"])


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_approvalworkflow_stage_name_approvalmatrixrule_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('employees', '0002_employee_address_employee_branch_employee_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalmatrixrule',
            name='approver_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_matrix_assignments', to='auth.group'),
        ),
        migrations.AddField(
            model_name='approvalmatrixrule',
            name='assignment_type',
            field=models.CharField(choices=[('fixed_employee', 'Fixed employee'), ('department_head', 'Requesting department head'), ('role', 'Employee role')], default='fixed_employee', max_length=30),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_approval_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvalmatrixrule',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_matrix_assignments', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='approvalworkflow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned for correction'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
        migrations.RunPython(
            backfill_approval_routing,
            migrations.RunPython.noop,
        ),
    ]
