# Generated by Django 6.0.6 on 2026-08-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_purchaseorderapprovalworkflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmatrixrule',
            name='assignment_type',
            field=models.CharField(choices=[('fixed_employee', 'Fixed employee'), ('role', 'Employee role')], default='fixed_employee', max_length=30),
        ),
    ]
